### ISSUE TITLE
move generated PNG/SVG files out-of-the-way?

### ISSUE THREAD

**Issue by gliptak** [asciidoctor/asciidoctor-diagram#102]
Running results in a number of generated PNG/SVG/cache files placed into the same folder as the ```*.adoc```. Would it be possible to clean them up after the inclusion on the PDF/EPUB? Or maybe generate in TMP directory? Thanks

**Comment by pepijnve** [comment]
These aren't really temp files. They contain a checksum of the diagram source code and some metadata which allows the extension to avoid regenerating diagrams every time asciidoctor is run.
We can't really clean them up automatically since that would defeat their purpose as cache files for the next run.

I do think it would be a good idea to write those files somewhere a bit more out of sight. Would an `.asciidoctor-diagram` dot directory next to the `.adoc` file work for you?

**Comment by gliptak** [comment]
Yes out-of-site is a good goal and another goal could be exclusion from under source control. ```.asciidoctor-diagram``` works for both.

**Comment by mojavelinux** [comment]
Agreed, though perhaps `.asciidoctor/diagram` so other extensions can use the directory too.

**Comment by pepijnve** [comment]
Yep, that sounds like a better plan. Ideally that `.asciidoctor` directory location would be provided by asciidoctor to the extension as a cache dir or something like that. But for the time being I'll implement this in the diagram extension itself.
Where should we put it? Relative to the base dir?

**Comment by mojavelinux** [comment]
> Where should we put it? Relative to the base dir?

That sounds right.
