### ISSUE TITLE
How to reduce the duplicated filename?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-diagram#109]
I have a Asciidoc as follows:

```
== Test Plant UML

plantuml::puml/class.puml[format=svg, alt="Class diagram", target="target/class"]
```

The `class.pum` is as follows:

```
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
```

run `asciidoctor -r asciidoctor-diagram  sample.adoc`, then it gernerates the UML diagram in  `target/`, named `class.svg`.

I think the filename is duplicated.

**Could I not define the target filename, use the original name?** 

For examle, 

* the original filename `myclass.puml`, 
* set the `target` attribute is `target/` or `target/{filename}`,
* then gernerate the target filename is `target/myclass.svg`

**Comment by mojavelinux** [comment]
See https://github.com/asciidoctor/asciidoctor-diagram#image-output-location

If that section is unclear, let's improve it.

**Comment by pepijnve** [comment]
I'm not sure what the question is here. What you're describing is how it currently works. If in your example you omit the `target` attribute and invoke asciidoctor with the `-D target` option, `class.svg` will be generated in target.

Currently diagrams are always generated as `<output dir>/<source basename>.<image type extension>`. In other words the directories of the source are stripped off. It might be a good idea to retain these so that we don't overwrite images when you have something like `a/class.puml` and `b/class.puml`.

**Comment by pepijnve** [comment]
@diguage is any further action required on this issue?

**Comment by diguage** [comment]
@pepijnve No. I close the issue.
