### ISSUE TITLE
Cannot find GraphViz

### ISSUE THREAD

**Issue by PrimaryFeather** [asciidoctor/asciidoctor-diagram#126]
First of all, kudos for this fantastic extension! 

I wanted to add a _PlantUML_ diagram to my document today, but found the following image instead of the diagram:

![diagram-classes](https://cloud.githubusercontent.com/assets/547347/18173012/33ac60cc-7068-11e6-9896-e6f47904a44a.png)

My `dot` executable actually lies here:

```bash
> which dot
/usr/local/bin/dot
```

I executed the command shown in the image, with the following result:

```bash
> java -jar plantuml.jar -testdot
The environment variable GRAPHVIZ_DOT has not been set
Dot executable is /usr/local/bin/dot
Dot version: dot - graphviz version 2.38.0 (20140413.2041)
Installation seems OK. File generation OK
``` 

So I tried adding that environment variable. That changed the first line to:

    The environment variable GRAPHVIZ_DOT has been set to /usr/local/bin/dot

But, alas, the output of `asciidoctor-diagram` is still the same.

Here's some information about my system:

* OS X 10.11.6
* asciidoctor 1.5.4
* asciidoctor-diagram 1.5.1
* ruby 2.2.3
* java 1.8.0_66

If you've got any ideas about what else I could try, I'm all ears! In any case, thanks a lot in advance!!

**Comment by pepijnve** [comment]
The diagram extension uses `$PATH` to try and locate `dot` automatically. If it can't find it that way it invokes plantuml without specifying the location of `dot` essentially leaving it up to plantuml to try and locate it. If that fails as well then you'll get this kind of error image as a result.

Since `which` is able to locate `dot` and that use the path as well asciidoctor-diagram should be able to find it too. A bit puzzling that that's failing.
If you're comfortable doing some mild hacking, the point where the path to `dot` is resolved is in the (plantuml integration code)[https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/plantuml/extension.rb#L32). The actual lookup is done by the [which function](https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/util/which.rb#L5)
You could add some `puts` statements in which to see which alternatives its trying.

I'm planning on adding verbose logging output to help in diagnosing issue #124. I can add extra logging here as well. Seems like it could be useful in general.

If you need a quick workaround, you can manually specify the location of `dot` via a document attribute. Both the `dot` and `graphvizdot` attribute will work. Runing asciidoctor with `-a dot=/usr/local/bin/dot` should do the trick.

**Comment by PrimaryFeather** [comment]
Thanks a lot for your extremely fast answer!

This morning, I installed pry, ready to debug into the code you pointed me at; for this, I set up a quick test-project. And, lo and behold! - of course, in that test project, the diagram showed up just fine.

So I went back to my original project and ran `asciidoctor` again, but still: the old output. Then I added another diagram somewhere else, and it suddenly showed up. :open_mouth: I thought I had tried that already yesterday ... but I guess my memory is tricking me. 

It seems the old image was simply cached somehow, probably still from the first time I ran the extension (at which time I didn't have graphviz installed). Classical.

So, my apologies for the interruption — as I should have expected, the problem was purely on my side. Now it works just fine! Nothing to fix on your side, which is probably good news, at least. :wink:

Again, thanks for your great work on this!

**Comment by mojavelinux** [comment]
> It seems the old image was simply cached somehow

You may have discovered a nice tip for the README. The README makes no mention of the cache, so new users could easily get bitten by this lack of knowledge. Perhaps the README should state that the generated images are cached to avoid redundant work, where they are cached, and when they get updated. It can then recommend clearing the cache if something is going wrong.

**Comment by PrimaryFeather** [comment]
You're right, that would definitely make sense! A little background information might have pointed me in the right direction sooner.

**Comment by hadil-man** [comment]
I wanted to show PlantUML diagram , but i found the following image instead of the diagram 
file does not exist
Cannot find GraphViz 
please any help
