### ISSUE TITLE
Add support for mscgen

### ISSUE THREAD

**Issue by oddhack** [asciidoctor/asciidoctor-diagram#167]
I have a bunch of MSC (Message Sequence Chart) files to include in my document, and the 'mscgen' converter installed which can turn them into SVG or other output formats. Would it be straightforward to plug a new input format into asciidoctor-diagram?

**Comment by pepijnve** [comment]
Absolutely. Most of the code is shared between the various diagram types. The amount of CLI tool specific code is very small, so adding additional ones is straightforward.
First you need to create the block and block macro processors (see https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/shaape/extension.rb)
Then add a file for your new diagram type that registers the processors when it is required (see https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/shaape.rb)
Finally, require that file from asciidoctor-diagram.rb so that it is available when the main asciidoctor-diagram file is required (see https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram.rb)

**Comment by pepijnve** [comment]
I had some free time this evening so I went ahead and integrated support for mscgen.

**Comment by oddhack** [comment]
Nice! Thanks very much - I will give it a try soon.

**Comment by vinipsmaker** [comment]
Could the comment https://github.com/asciidoctor/asciidoctor-diagram/issues/167#issuecomment-332746557 be converted into a `HACKING.adoc` file and be included in the repo?
