### ISSUE TITLE
Diagrams in tables don't respect --destination-dir.

### ISSUE THREAD

**Issue by brtjdcole** [asciidoctor/asciidoctor-diagram#201]
Compare the locations of graphviz_test and graphviz_test2 in the following doc rendered with `asciidoctor -r asciidoctor-diagram test.adoc --destination-dir /tmp/out`. The diagram outside the table will land in /tmp/out the diagram inside will land in the source directory.

asciidoctor (1.5.8)
asciidoctor-diagram (1.5.11)

```
Simple Test Document
====================

|===
|Type | Example

|graphviz
a|[graphviz, graphviz_test, svg]
....
digraph test {
  A -> B
  B -> C
  C -> D
}
....

|===

[graphviz, graphviz_test2, svg]
....
digraph test {
  A -> B
  B -> C
  C -> D
}
....
```

**Comment by pepijnve** [comment]
Issue resolved?

**Comment by mojavelinux** [comment]
I tested this scenario and it works for me.

**Comment by brtjdcole** [comment]
Same versions?

**Comment by mojavelinux** [comment]
Ooops, my mistake. I wasn't testing with the right flags.

Yes, the diagram in the table doesn't respect the destination directory. It ends up in the current directory instead.

If I specify `imagesoutdir` explicitly, then it works.

@pepijnve I think the problem is that the options doesn't get inherited to the nested document (for the AsciiDoc table cell). If `document.nested?` is true, then you need to look at the parent document. (Perhaps the options should inherit, I'm not sure).

**Comment by mojavelinux** [comment]
It would need to be here: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/document.rb#L255

**Comment by pepijnve** [comment]
Nested documents? That's a new concept for me. Didn't realise those even existed 😄 
I'll get this sorted out asap.

**Comment by mojavelinux** [comment]
Yep. An AsciiDoc table cell gets it's own document object. See https://github.com/asciidoctor/asciidoctor/blob/b853f5264c4fd452c8319e853268a8d353532140/lib/asciidoctor/table.rb#L289-L308

**Comment by pepijnve** [comment]
Going off on a tangent a bit, but what's the reason for this? Does a table need to have its own context for numbering, xrefs, etc?

**Comment by mojavelinux** [comment]
The reason is historical. AsciiDoc Python invokes a subprocess to convert an AsciiDoc table cell. Asciidoctor improved on this by making it a subdocument instead. Changing that assumption now would be very difficult. We'd likely need to introduce a new table style if we wanted to have just normal block-level processing.

> Does a table need to have its own context for numbering, xrefs, etc?

These get inherited (see https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/document.rb#L253-L276). So it's more of a subdocument than a standalone document.
