### ISSUE TITLE
Upstream build is running against release instead of master

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-diagram#220]
For some reason, the upstream build is using Gemfile instead of Gemfile.master. (See https://travis-ci.org/asciidoctor/asciidoctor-diagram/builds/512769596). It's possible something changed in Travis' config merge logic that caused this to stop working.

Whatever asciidoctor-reveal.js is doing is still working, so that might be a useful reference when debugging the problem.

**Comment by mojavelinux** [comment]
The build log reads:

```
export BUNDLE_GEMFILE=$PWD/Gemfile
```

when it should read:

```
export BUNDLE_GEMFILE=$PWD/Gemfile.master
```

**Comment by mojavelinux** [comment]
What's strange is that it works fine in the main build. (See https://travis-ci.org/asciidoctor/asciidoctor-diagram/jobs/512774295)

**Comment by pepijnve** [comment]
I had another look at https://travis-ci.org/asciidoctor/asciidoctor-diagram/jobs/544597576/config
No idea what's wrong. The input looks correct to me.

**Comment by mojavelinux** [comment]
I'm going to try a few things to see if it's an ordering issue.

**Comment by pepijnve** [comment]
I just reread the Travis doc. Default `merge_mode` is `merge` which replaces section of the config. Due to the I think we're basically overwritten the entire `matrix` section. I added `merge_mode: deep_merge` which, if I understand it correctly, will merge the two `matrix` maps. Maybe that fixes things.

**Comment by mojavelinux** [comment]
I'll try both. Stay tuned. I'm kicking builds.

**Comment by pepijnve** [comment]
The build probably got broken in 81c5f930d942838a739bdf823a69248c7134c75b. Before then the main `.travis.yml` didn't contain a `matrix` section and the default merge of the exclude in the upstream file did the right thing.

**Comment by mojavelinux** [comment]
I'm convinced this is a bug in Travis CI. Fortunately, I think I know a workaround.  I'm testing my theory.

**Comment by pepijnve** [comment]
Looking at https://docs.travis-ci.com/user/build-matrix/ it's not really well defined what happens if you have both an explicit `include` and an explicit `exclude` in the `matrix` for the same jobs.

I think you're last change where we use the default merge mode (i.e., replace the `matrix` section) will do the trick.

**Comment by pepijnve** [comment]
https://travis-ci.org/asciidoctor/asciidoctor-diagram/builds/544615987
Success!

**Comment by mojavelinux** [comment]
Yep, that works:

```
Using Gemfile.master
$ export BUNDLE_GEMFILE=$PWD/Gemfile.master
```

So we have what we need, at least.

**Comment by mojavelinux** [comment]
So the trick for now is:

```yml
matrix:
  include:
  - rvm: 2.6
    gemfile: Gemfile.master
```

Probably easier to understand anyway.
