### ISSUE TITLE
Upgrade to new WaveDrom

### ISSUE THREAD

**Issue by drom** [asciidoctor/asciidoctor-diagram#225]
I have a new version of wavedrom v2.1.2 here: https://github.com/wavedrom/wavedrom
it comes with browserless CLI. https://github.com/wavedrom/wavedrom/releases/tag/v2.1.2
It is a single file application and requires only `node.js` to run.

```bash
node wavedrom.js -i sourceWaveDrom.json5 > result.svg
```
Current version can produce only `SVG`. Do we need `PNG`?

I can release `PNG` capable version, but that would require normal `npm install` flow.

_Originally posted by @drom in https://github.com/asciidoctor/asciidoctor-diagram/issues/190#issuecomment-500915750_

**Comment by pepijnve** [comment]
> It is a single file application and requires only node.js to run.

Would it be possible to provide an executable wrapper script for this? (see https://medium.com/netscape/a-guide-to-create-a-nodejs-command-line-package-c2166ad0452e for an example). The code is already searching for an executable file named `wavedrom`. If the NPM package can provide that it makes my life a bit easier.

Is there a way to query the version number via the CLI? That will be necessary so I can switch between the older and newer versions of wavedrom.

> Current version can produce only SVG. Do we need PNG?

The asciidoctor extension currently reports PNG as a supported output format since the old version was able to produce this. The supported output formats are static at the moment in asciidoctor-diagram. The worst that will happen though is a runtime error if people request pngs with the newer version of wavedrom.

**Comment by drom** [comment]
Make sense. Will fix.

**Comment by drom** [comment]
I have published `wavedrom-cli` v2 on `npm`
Here is the source code: https://github.com/wavedrom/cli

Generates SVG or PNG
`wavedrom-cli --version` for version number
`wavedrom-cli --help` for all options

**Comment by pepijnve** [comment]
Perfect. Since the name of the command differs from the earlier version (was just `wavedrom`) I probably don't even need a version check. :+1:
