### ISSUE TITLE
Resolve paths in block macros similar to asciidoc's include directive

### ISSUE THREAD

**Issue by basvandijk** [asciidoctor/asciidoctor-diagram#230]
To quote the [documentation of diagram block macros](https://github.com/asciidoctor/asciidoctor-diagram/#diagram-block-macro) regarding path resolving:

> When the source file name is a relative path it is resolved with respect to the location of the document being processed.

Here the "location of the document being processed" means the path that the `asciidoctor` tool was applied to.

A more user-friendly, consistent and composable behavior would be if path resolving would work exactly like the [asciidoc include directive](https://asciidoctor.org/docs/user-manual/#include-resolution):

> * If the include directive is used in the main (top-level) document, relative paths are resolved relative to the base directory. (The base directory defaults to the directory of the main document and can be overridden from the CLI or API).
> * If the include directive is used in a file that has itself been included, the path is resolved relative to the including (i.e., current) file.

The second point is especially important for composability:  often, big documents are broken up in several `.adoc` files that form a hierarchy. A master or super document might include other sub documents which might again include other sub documents. It's important that users can apply `asciidoctor` to sub documents alone instead of always only applying it to the super document. 

For this to work paths to diagrams referenced in sub documents need to be relative to the sub document such that they can be resolved both when processing the sub document alone or when processing the super document.

Also, block macros are very similar to include directives; they both reference external files. So it would make sense to have consistent behavior regarding path resolving. The fewer surprises the better.

**Comment by mojavelinux** [comment]
AsciiDoc (as implemented by Asciidoctor or AsciiDoc Python) does not (yet) have subdocuments. There's simply no such concept. Therefore, we cannot base decisions on locations of these documents because that's just not how it works (currently).

This has been discussed many times and we are still making plans for a solution. See https://github.com/asciidoctor/asciidoctor/issues/650#issuecomment-433689572

**Comment by mojavelinux** [comment]
As I've discussed before, we could introduce a document macro (not preprocessor directive) that would have awareness of the structure of the document and could thus establish a "current context". This will never be how the include directive works because the include directive combines files before the lines are parsed.

**Comment by basvandijk** [comment]
I think the [`indir` extension](https://github.com/asciidoctor/asciidoctor-extensions-lab/pull/100) might do exactly what I need. I'll try it out and report back here.

**Comment by pepijnve** [comment]
Closing due to lack of feedback
