### ISSUE TITLE
Variable substitution issue when converting to docbook

### ISSUE THREAD

**Issue by mijlouis** [asciidoctor/asciidoctor-diagram#239]
Hello,
I have a document test-plant.uml which looks like 

`= Project Title
author-prename author-lastname <author-email@company.com>
:toc:
**:test: plantUml/**

== Some Headline

.Architecture
image::./assets/Sample.png[Architecture]

[plantuml, "{test}_gen_diagram-classes", png]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock

Bob -[#red]> Alice : hello
Alice -[#0000FF]->Bob : ok
....

.PlantUML Demo 01
plantuml::./assets/Demo-01.puml["**{test}**_gen_Demo-01", svg]

.PlantUML Demo 02
plantuml::./assets/Demo-02.puml["**{test}**_gen_Demo-02", svg]
`

I'm using a global variable **test** to store generated images by plantUml into a subfolder called **plantUml** as shown in code above. 

Project folder structure is as follows
![image](https://user-images.githubusercontent.com/43267376/64869472-bcc8b800-d641-11e9-8611-f7bc33f703df.png)

When I convert to docbook with following command

> asciidoctor -r asciidoctor-diagram -b docbook -a leveloffset=+1 -a imagesdir=assets test-plantuml.adoc

images are generated as follows:
![image](https://user-images.githubusercontent.com/43267376/64869722-3496e280-d642-11e9-9bd6-ddbfb2e9651f.png)

I would expect that the images generated from plantUML are generated in a subfolder **plantUml** of **imagesdir**.

The only way to achieve this is when I declare the variable in the content and not in the header.

![image](https://user-images.githubusercontent.com/43267376/64870681-06b29d80-d644-11e9-81d5-e393fb18435a.png)

Is this the intended behavior or am I doing something wrong?

Thanks for any feedback on this,
Michael 
(Example document and content attached.)

[Asciidoctor-Diagram-Variable-Substitution-Issue.zip](https://github.com/asciidoctor/asciidoctor-diagram/files/3610459/Asciidoctor-Diagram-Variable-Substitution-Issue.zip)

**Comment by mojavelinux** [comment]
To get attribute substitution in a block attribute, the value must be enclosed in single quotes. The single quotes enable "interpolation" in the AsciiDoc sense. See https://asciidoctor.org/docs/user-manual/#attribute-list-substitutions

**Comment by pepijnve** [comment]
@mijlouis does @mojavelinux answer solve the problem for you? I'm going to mark this as closed since the attribute substitution is handled by asciidoctor itself; not really a diagram specific issue.

**Comment by pepijnve** [comment]
ok, reopening for further investigation then

**Comment by pepijnve** [comment]
@mojavelinux who's responsibility is it to trigger the substitution logic? asciidoctor core or the extension receiving the attributes?

**Comment by mojavelinux** [comment]
First, I was mistaken. Attribute references are always resolved in a block attribute list. So the quotes aren't even necessary:

```
[plantuml,{test}_gen_diagram-classes,png]
```

(If you try that with the `asciidoctor` command, you will see it works).

The attributes are parsed before the extension runs, so there's nothing the extension should have to do here.

If that doesn't work, I'd look at how Asciidoctor is being invoked, because something is wrong. Given we're looking at screenshots from the IntelliJ plugin, my hunch is that it's how that plugin is handling the diagrams for the preview.

**Comment by pepijnve** [comment]
@mijlouis sounds likely that this is an Asciidoctor IntelliJ plugin issue indeed. Are you having the same problem when you run asciidoctor from the command line?

**Comment by mijlouis** [comment]
@pepijnve Yes, I used the command line to do the conversion.
The command I am using is 

asciidoctor -r asciidoctor-diagram -b docbook -a leveloffset=+1 -a imagesdir=assets test-plantuml.adoc

**Comment by mojavelinux** [comment]
That definitely works for me. What version of Asciidoctor are you using?

You'll probably need to provide a sample project for us to help you debug further.

**Comment by mijlouis** [comment]
@mojavelinux I am using 
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.1p33 (2019-01-30 revision 66950) [x64-mingw32]) (lc:CP850 fs:Windows-1252 in:CP850 ex:CP850)

![image](https://user-images.githubusercontent.com/43267376/65018648-e297da80-d929-11e9-98ae-03fcddc7a6a2.png)

I provided already a sample project as attachment to the first Post. Is it not available ?

Thanks

**Comment by mojavelinux** [comment]
> I provided already a sample project as attachment to the first Post. Is it not available ?

My mistake. I missed that.

**Comment by mojavelinux** [comment]
Aha!

The problem is this attribute assignment: `-a leveloffset=+1`. That demotes the document title to a regular section title and demotes the document header to regular content. That means the implicit author line gets parsed a paragraph:

```
author-prename author-lastname <author-email@company.com>
:toc:
:test: plantUml/
```

Since the attribute entries below the implicit author line are directly adjacent, they also get swallowed by the paragraph as normal content (which you can see in the output document).

There are two solutions to this problem:

* The first is to stop using `-a leveloffset=+1` globally (which probably isn't what you want anyway since it erases the document header).
* The second is to define the author using explicit attributes instead of an implicit attribute line:
    ```
    = Project Title
    :author: author-prename author-lastname
    :email: author-email@company.com
    ```

While you still lose the document header in the second solution, at least it doesn't corrupt the attribute entries (so you can reference their values).

In the end, this has nothing to do with Asciidoctor Diagram.

**Comment by mijlouis** [comment]
@mojavelinux and @pepijnve, thank you very much for your support and for helping me to solve the issue. The answer from @mojavelinux solved my problem.
Awesome!

**Comment by mojavelinux** [comment]
Glad to hear it!
