### ISSUE TITLE
Add support for utxt (unicode plain text) on PlantUML

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-diagram#253]
I believe that currently only `txt` is supported on PlantUML right? I think we should also support `utxt` (unicode plain text).

Reference: https://plantuml.com/fr/ascii-art

**Comment by Mogztter** [comment]
@pepijnve I believe this is now fixed right? Should I close this issue?

**Comment by pepijnve** [comment]
There are some loose ends I still wanted to check.  When you request the `atxt` output mode, the diagram plugin sends a request with `Accept: text/plain; charset=us-ascii` to the java server. Strictly speaking that's not correct since PlantUML may still generate Unicode characters if your diagram source contains non-ASCII text. It would probably be more correct to use some custom mime type instead.

**Comment by Mogztter** [comment]
Ok :+1:
