### ISSUE TITLE
Wrong resolution of `:to_dir` in Windows when including diagram and PDF with relative path

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-diagram#298]
We have this issue in the maven-plugin which still reproduces with the latests versions ONLY in Windows: https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/351.

Running directly the gems (see https://github.com/abelsromero/asciidoctor-demo/tree/analysis) and adding `puts` I was able to track the issue to `doc_option` method here https://github.com/asciidoctor/asciidoctor-diagram/blob/fd8ab7d9eb9d5de3c55a0e27c4276206c728a917/lib/asciidoctor-diagram/diagram_processor.rb#L317

For some unknown reason, while running the HTML backend it returns the correct path `C:/Users/MY_USER/temp/asciidoctor-demo/target`. However, for the PDF backend it returns `C:/Users/MY_USER/temp/asciidoctor-demo/target/C:/Users/MY_USER/temp/asciidoctor-demo/target` -> basically, the absolute path concatenated twice 🤷 

A file as simple as is enough
```adoc
= Demo Document
Author
:toc: preamble
:icons: font
:sectnums!:

plantuml::demo.puml[]
```

Before scalating to asciidoctor-pdf and asciidoctor, I wonder if there could be some options manipulation done here that would explain this.

**Comment by pepijnve** [comment]
This reminds me of https://github.com/asciidoctor/asciidoctorj-diagram/issues/7. That double absolute path is a side effect of safe mode path normalisation. Your best to control where images get written is to set `imagesoutdir`.

**Comment by abelsromero** [comment]
> safe mode path normalisation

is that what asciidoctor.path_resolver does? Even with setting extra fields we can work this out, it's still a very odd behauvior.

**Comment by pepijnve** [comment]
Yes the path resolver can do that. See https://github.com/asciidoctor/asciidoctor/blob/7f61a30b20da6f01d5b3809da33baec2e5efae89/lib/asciidoctor/path_resolver.rb#L332

Not sure if that's what's happening here, but I've seen these double absolute paths before and escaping the safe mode jail was the root cause there.

**Comment by abelsromero** [comment]
No luck with `imagesoutdir`, pretty sure the problem comes from the cache used to place the metadata, not the image itself https://github.com/asciidoctor/asciidoctor-diagram/blob/fd8ab7d9eb9d5de3c55a0e27c4276206c728a917/lib/asciidoctor-diagram/diagram_processor.rb#L149.

Debugging I see that the image file path takes the value from `imagesoutdir`, but the metadata path still contains the double path.

**Comment by pepijnve** [comment]
You can use `diagram-cachedir` to override that. See https://github.com/asciidoctor/asciidoctor-diagram/blob/fd8ab7d9eb9d5de3c55a0e27c4276206c728a917/lib/asciidoctor-diagram/diagram_processor.rb#L282

**Comment by abelsromero** [comment]
Setting both `imagesoutdir` and `diagram-cachedir` but there are couple of things I don't understand:
*  What is this global attribute and why do I need to prefix it when the ruby code does not have the 'diagram-' prefix?
* Is it safe to use? or in other words, any reason why is not documented in the readme?

**Comment by pepijnve** [comment]
> What is this global attribute and why do I need to prefix it when the ruby code does not have the 'diagram-' prefix?

The 'global' thing is just an internal name. The method in question looks up the attribute at the block (macro) level with the given name and falls back to looking it up with `diagram-` stuck in front of it at the document level.

> Is it safe to use? or in other words, any reason why is not documented in the readme?

I'm not planning on stripping this back out. The explicit override option via an attribute is here to stay. What might change in the future is the default computed value for the cache directory. No concrete plans at the moment though.
Why is it not yet in the README? Because I don't get paid to develop this software 😄 Just haven't gotten round to updating it.

**Comment by abelsromero** [comment]
Thanks for your awesome help! I'll send a PR for the readme later, and chase the issue on the asciidoctor side.
Yesterday I found out the double path seems to be triggered when setting an absolute path in "to_file" option but only from AsciidoctorJ, not from Ruby cli (even though the path is not duplicated on the Java side).
