### ISSUE TITLE
Do not require dot on path for sequence diagrams

### ISSUE THREAD

**Issue by vstriz** [asciidoctor/asciidoctor-diagram#71]
PlantUML is able to generate sequence diagrams without using *dot*. However the asciidoc-diagram extension still fails with: 

ERROR: Failed to generate image: PlantUML image generation failed: Bad Req
uest java.io.IOException: Could not find GraphViz 'dot' tool
        at org.asciidoctor.diagram.PlantUML.getGraphviz(PlantUML.java:24)
        at org.asciidoctor.diagram.PlantUML.generate(PlantUML.java:35)
        at org.asciidoctor.diagram.CommandProcessor.processRequest(CommandProcessor.java:34)
        at org.asciidoctor.diagram.CommandProcessor.processRequest(CommandProcessor.java:11)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

I worked around it by creating an empty "dot.bat" file that does nothing and then it works and shows the diagrams correctly, which proves it doesn't actually need dot. This is true only for sequence diagrams.

**Comment by pepijnve** [comment]
@vstriz the processing code tries to find the dot executable regardless of the code of the diagram it's processing. The diagram code itself is treated as an opaque string and simply passed to plantuml.

I could the dot lookup conditional but that would require parsing the diagram code since there's no simple way to detect that a bit of plantuml code is a sequence diagram (i.e., there's no `@startsequence` to check for).

The current code in `org.asciidoctor.diagram.PlantUML` is pretty high-level. It basically build a list of command line parameters to pass to plantuml. It might be possible, by making the code more low-level, to get plantuml to parse the diagram code, then query the diagram type and based on that decide to look for dot or not. If that's possible I'm willing to implement this change. If not, then I'm not inclined to do this since I don't want to maintain a parallel plantuml code parser.

**Comment by vstriz** [comment]
I agree that you shouldn't implement parallel parser. What about this alternative. Look for dot executable as you do now and set on options it if you find it. However If you don't find it, don't throw the exception immediately but call to plantuml anyway. I am assuming that plantuml will throw an exception of its own if it can't run dot and needs it. You can then either catch that and wrap it in your own, or just let it propagate as is.

**Comment by pepijnve** [comment]
3b789df9e3b07c0e970211f55983af2171219db4 implements the logic discussed above. The Ruby code tries to find `dot`, but doesn't raise an error if it can't. If we've located it already it gets passed on to PlantUML, otherwise we let PlantUML try to find it on its own if necessary.
