### ISSUE TITLE
ASCIImage support

### ISSUE THREAD

**Issue by nikolay** [asciidoctor/asciidoctor-diagram#72]
It would be nice to have [ASCIImage](http://asciimage.org/) as an extension similar to the diagramming one.

There's a Ruby-based library already: https://github.com/Oblomov/asciimage-ruby

Originally submitted here: https://github.com/asciidoctor/asciidoctor/issues/1317

**Comment by pepijnve** [comment]
@nikolay given that there's already a Ruby port for this it shouldl be pretty trivial to integrate. I'll try to get this in the next release. Thanks for the suggestion.

**Comment by nikolay** [comment]
@pepijnve Thank you!

**Comment by pepijnve** [comment]
I spent some time reviewing this in more detail and it's not as simple as I thought.

From a technical perspective the code you pointed to is a bit hard to reuse. It's not published as a gem, so depending on it that way isn't possible yet. It doesn't have any license on it yet, so I can't just integrate it either. Making my own asciiimage interpreter would be a fun exercise of course :D

From a practical perspective I'm not sure how you would actually use this in an asciidoc document. The more complex icons require code to do the 'hole punching' part since there's no way to define styling in the icon description itself. You could embed some ruby in the asciidoc document of course, but I'm not convinced that would be practical at all.

Could provide an example of how you would want to use this in practice? If there are no technical limits, what would the ideal integration in asciidoc look like?

**Comment by mojavelinux** [comment]
>  It's not published as a gem, so depending on it that way isn't possible yet. 

I'd say that's definitely a prerequisite.

> Could provide an example of how you would want to use this in practice?

I'd really like to see an example as well.

**Comment by nikolay** [comment]
@pepijnve @mojavelinux Thank you guys! Let me try to address the first issue with the author and will work on an example for you as well!

**Comment by pepijnve** [comment]
Marked this issue as deferred. While it would be a nifty feature to implement I have my doubts about its usefulness. If anyone feels like contributing a patch for this, those are always welcome of course.

**Comment by pepijnve** [comment]
Since there's been no news on this and its usefulness seems limited I'm going to close this issue. Feel free to reopen if there are any updates.

**Comment by timofonic** [comment]
I would love more support for ASCII rendering to images...

And even embed schematic/pcb code into asciidoc :D

http://makezine.com/2010/02/04/ascii-schematic-editor/
http://kicad-pcb.org/help/file-formats/
